### ISSUE TITLE
HeapOutOfBounds with program that uses a big struct (C code)

### ISSUE THREAD

**Issue by orestisfl** [bytecodealliance/lucet#450]
**What I did:**
1. Get the code: `curl https://raw.githubusercontent.com/SideChannelMarvels/Deadpool/master/wbs_aes_nsc2013_variants/target/nosuchcon_2013_whitebox_noenc.c -o a.c`
2. `wasm32-wasi-clang a.c -o a.wasm`
3. `lucetc-wasi a.wasm -o a.so`
4. `RUST_BACKTRACE=full lucet-wasi a.so`
Output:
```text
thread 'main' panicked at 'lucet-wasi runtime error: Runtime fault: FaultDetails { fatal: false, trapcode: Some(HeapOutOfBounds), rip_addr: 139762745829839, rip_addr_details: Some(AddrDetails { in_module_code: true, file_name: Some("/tmp/xx/a.so"), sym_name: None }) }', lucet-wasi/src/main.rs:277:23
stack backtrace:
   0:     0x5630255f55c4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5630255f55c4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5630255f55c4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5630255f55c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x56302562d4fc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x5630255e99a7 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x5630255f9e2e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5630255f9e2e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5630255f9e2e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x5630255f9b21 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x5630255fa600 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:468
  11:     0x5630255fa0ce - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x5630255fa00f - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x5630253a30ee - lucet_wasi::main::ha6c45bec3f881e2b
  14:     0x56302539af03 - std::rt::lang_start::{{closure}}::hcc48f9e909c061a9
  15:     0x5630255f9f53 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  16:     0x5630255f9f53 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  17:     0x56302560aeaa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  18:     0x5630255faacd - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  19:     0x5630255faacd - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  20:     0x5630255faacd - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  21:     0x5630253a3cb2 - main
  22:     0x7f1d0d2fab97 - __libc_start_main
  23:     0x56302539642a - _start
  24:                0x0 - <unknown>
```

Btw, to execute correctly, this program requres additional files and argument. However, the fault is triggered without them. For reference, here is a successful invocation of a native executable compiled with clang:
1. `clang a.c`
2. `./a.out 74657374746573747465737474657374`
```text
Input:    74 65 73 74 74 65 73 74 74 65 73 74 74 65 73 74 
Enc in:   74 74 74 74 65 65 65 65 73 73 73 73 74 74 74 74 
Enc out:  4C 74 7B 5C 53 54 DB 2B 6D 13 39 C9 31 81 33 40 
Output:   4C 74 7B 5C 53 54 DB 2B 6D 13 39 C9 31 81 33 40 
```
Attached: needed file, `wbt_noenc` [wbt_noenc.zip](https://github.com/bytecodealliance/lucet/files/4326314/wbt_noenc.zip) (extract in same directory).

Any ideas on how to fix this?
If this is a bug, workarounds to avoid it would be very helpful.

Thank you

**Comment by acfoltzer** [comment]
Thank you for this report! While I initially thought this was happening because of the missing argument and file (the C program doesn't check whether either are valid, and would crash without them), this actually appears to be an issue with large stack variables. I reduced it down all the way to:

```c
int main(int argc, char *argv[])
{
    /* // doesn't crash */
    /* char x[0x105E4]; */

    // crashes
    char x[0x105E5];

    return 0;
}
```

We'll definitely investigate; unfortunately I don't have a workaround to suggest at the moment.

**Comment by sunfishcode** [comment]
It is possible to control the stack size, with something like `-Wl,-z,stack-size=1048576` to set a larger size.

Another relevant option is `-Wl,--stack-first`, which instructs the linker to place the stack allocation to start at address 0, so that when the program runs out of stack space (growing down), addresses wrap around to very large 32-bit values, which will very likely trap.

Eventually we'd like for the LLVM wasm backend to have the ability to check for overflow whenever extending the stack, but it's not implemented yet.

**Comment by orestisfl** [comment]
Thank you very much to both. @sunfishcode's workaround works great for me! Please, feel free to re-purpose / edit the original report as you wish.
